name: CI - Build

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  KIOSK_API_KEY: ${{ secrets.KIOSK_API_KEY }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  NEXT_PUBLIC_AD_FETCH_INTERVAL: ${{ secrets.NEXT_PUBLIC_AD_FETCH_INTERVAL }}
  NEXT_PUBLIC_AD_ROTATION_INTERVAL: ${{ secrets.NEXT_PUBLIC_AD_ROTATION_INTERVAL }}
  NEXT_PUBLIC_DARK_MODE_FETCH_INTERVAL: ${{ secrets.NEXT_PUBLIC_DARK_MODE_FETCH_INTERVAL }}
  NEXT_PUBLIC_DARK_MODE_MAP_ID: ${{ secrets.NEXT_PUBLIC_DARK_MODE_MAP_ID }}
  NEXT_PUBLIC_DEPARTURES_PAGINATION_INTERVAL: ${{ secrets.NEXT_PUBLIC_DEPARTURES_PAGINATION_INTERVAL }}
  NEXT_PUBLIC_DEPARTURES_UPDATE_INTERVAL: ${{ secrets.NEXT_PUBLIC_DEPARTURES_UPDATE_INTERVAL }}
  NEXT_PUBLIC_GENERAL_MESSAGE_UPDATE_INTERVAL: ${{ secrets.NEXT_PUBLIC_GENERAL_MESSAGE_UPDATE_INTERVAL }}
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
  NEXT_PUBLIC_HEALTH_FETCH_INTERVAL: ${{ secrets.NEXT_PUBLIC_HEALTH_FETCH_INTERVAL }}
  NEXT_PUBLIC_ICON_MESSAGE_PAGINATION_INTERVAL: ${{ secrets.NEXT_PUBLIC_ICON_MESSAGE_PAGINATION_INTERVAL }}
  NEXT_PUBLIC_ICON_MESSAGES_FETCH_INTERVAL: ${{ secrets.NEXT_PUBLIC_ICON_MESSAGES_FETCH_INTERVAL }}
  NEXT_PUBLIC_KIOSK_HEALTH_ENDPOINT: ${{ secrets.NEXT_PUBLIC_KIOSK_HEALTH_ENDPOINT }}
  NEXT_PUBLIC_LIGHT_MODE_MAP_ID: ${{ secrets.NEXT_PUBLIC_LIGHT_MODE_MAP_ID }}
  NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}
  NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependancies
        run: |
          npm ci
          npm install -g @sanity/cli@latest

      - name: Build Next
        run: npm run build:next

      - name: Build Sanity
        run: npm run build:sanity
