name: CI - Build

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
  NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
  NEXT_PUBLIC_MTD_API_GET_STOPS_URL: ${{ secrets.NEXT_PUBLIC_MTD_API_GET_STOPS_URL }}
  AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }} 
  NEXT_PUBLIC_KIOSK_HEALTH_ENDPOINT: ${{ secrets.NEXT_PUBLIC_KIOSK_HEALTH_ENDPOINT }}
  NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependancies
        run: |
          npm ci
          npm install -g @sanity/cli@latest

      - name: Build Next
        run: npm run build:next

      - name: Build Sanity
        run: npm run build:sanity
