name: Dependabot Auto Approve and Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  autoapprove-and-automerge:
    name: Dependabot Auto Approve and Merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Fetch Dependabot Metadata
      - name: Fetch Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Approve Pull Request
      - name: Approve Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            await github.rest.pulls.review({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              event: 'APPROVE'
            });
            console.log(`Approved PR #${pr_number}`);

      # Step 4: Enable Auto-Merge for Semver Patch Updates
      - name: Enable Auto-Merge for Semver Patch Updates
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              auto_merge: true
            });
            console.log(`Enabled auto-merge for PR #${pr_number}`);
      - name: Log PR Details
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`PR #${context.payload.pull_request.number}: ${context.payload.pull_request.title}`);
