name: 'Next.js Bundle Analysis'

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments!

env:
  AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
  KIOSK_API_KEY: ${{ secrets.KIOSK_API_KEY }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  NEXT_PUBLIC_AD_FETCH_INTERVAL: ${{ secrets.NEXT_PUBLIC_AD_FETCH_INTERVAL }}
  NEXT_PUBLIC_AD_ROTATION_INTERVAL: ${{ secrets.NEXT_PUBLIC_AD_ROTATION_INTERVAL }}
  NEXT_PUBLIC_DARK_MODE_FETCH_INTERVAL: ${{ secrets.NEXT_PUBLIC_DARK_MODE_FETCH_INTERVAL }}
  NEXT_PUBLIC_DARK_MODE_MAP_ID: ${{ secrets.NEXT_PUBLIC_DARK_MODE_MAP_ID }}
  NEXT_PUBLIC_DEPARTURES_PAGINATION_INTERVAL: ${{ secrets.NEXT_PUBLIC_DEPARTURES_PAGINATION_INTERVAL }}
  NEXT_PUBLIC_DEPARTURES_UPDATE_INTERVAL: ${{ secrets.NEXT_PUBLIC_DEPARTURES_UPDATE_INTERVAL }}
  NEXT_PUBLIC_GENERAL_MESSAGE_UPDATE_INTERVAL: ${{ secrets.NEXT_PUBLIC_GENERAL_MESSAGE_UPDATE_INTERVAL }}
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
  NEXT_PUBLIC_HEALTH_FETCH_INTERVAL: ${{ secrets.NEXT_PUBLIC_HEALTH_FETCH_INTERVAL }}
  NEXT_PUBLIC_ICON_MESSAGE_PAGINATION_INTERVAL: ${{ secrets.NEXT_PUBLIC_ICON_MESSAGE_PAGINATION_INTERVAL }}
  NEXT_PUBLIC_ICON_MESSAGES_FETCH_INTERVAL: ${{ secrets.NEXT_PUBLIC_ICON_MESSAGES_FETCH_INTERVAL }}
  NEXT_PUBLIC_KIOSK_HEALTH_ENDPOINT: ${{ secrets.NEXT_PUBLIC_KIOSK_HEALTH_ENDPOINT }}
  NEXT_PUBLIC_LIGHT_MODE_MAP_ID: ${{ secrets.NEXT_PUBLIC_LIGHT_MODE_MAP_ID }}
  NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}
  NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
  NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}

jobs:
  analyze:
    name: 'Analyze Bundle'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Cache npm Cache Directory
      - name: Cache npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      # 3. Setup Node.js with Dependency Caching
      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          check-latest: true
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # 4. Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # 5. Build Next.js Application
      - name: Build Next
        run: npm run build:next

      # 6. Analyze Bundle
      - name: Analyze Bundle
        run: npx nextjs-bundle-analysis report

      # 7. Upload Bundle Analysis Report
      - name: Upload Bundle Analysis Report
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: .next/analyze/__bundle_analysis.json

      # 8. Download Base Branch Bundle Stats
      - name: Download Base Branch Bundle Stats
        uses: dawidd6/action-download-artifact@v3
        if: success() && github.event.number
        with:
          workflow: next-js-bundle-analysis.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: .next/analyze/base

      # 9. Compare Current Bundle with Base Branch
      - name: Compare With Base Branch Bundle
        if: success() && github.event.number
        run: |
          ls -laR .next/analyze/base
          npx nextjs-bundle-analysis compare

      # 10. Generate Comment Body for PR
      - name: Generate Comment Body
        id: generate-comment
        if: success() && github.event.number
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat .next/analyze/__bundle_analysis_comment.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 11. Find Existing Comment in PR
      - name: Find Existing Comment
        uses: peter-evans/find-comment@v3
        if: success() && github.event.number
        id: find-comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '<!-- __NEXTJS_BUNDLE -->'

      # 12. Create New Comment if None Exists
      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v4
        if: success() && github.event.number && steps.find-comment.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.generate-comment.outputs.body }}

      # 13. Update Existing Comment
      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v4
        if: success() && github.event.number && steps.find-comment.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.generate-comment.outputs.body }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
